#!/bin/sh
#
# nodemgr Oracle Weblogic NodeManager service
#
# description: Oracle Weblogic NodeManager service

### BEGIN INIT INFO
# Provides: nodemgr
# Required-Start: $network $local_fs
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: Oracle Weblogic NodeManager service.
# Description: Starts and stops Oracle Weblogic NodeManager.
### END INIT INFO

### BEGIN DOCUMENTATION
# place it under /etc/init.d
# do not add .sh to the script
# make sure root owns this file and that its readable by everyone.
# 
# Usage:
# chkconfig --add [filename]
# service [filename] start
# the script will generate a stdout file under [DOMAIN_HOME]/nodemanager
### END DOCUMENTATION

. /etc/rc.d/init.d/functions

# Your WLS home directory (where wlserver is)
export MW_HOME="/opt/oracle/products/fmw"
export JAVA_HOME="/opt/java/jdk1.8_current"
export DOMAIN_HOME="/opt/oracle/Middleware/domains/esb_domain"
DAEMON_USER="esbdev"
PROCESS_STRING="weblogic.NodeManager"

source $MW_HOME/wlserver/server/bin/setWLSEnv.sh > /dev/null
export NodeManagerHome="$DOMAIN_HOME/nodemanager"
NodeManagerLockFile="$NodeManagerHome/nodemanager.log.lck"

# PROGRAM="$MW_HOME/wlserver_10.3/server/bin/startNodeManager.sh"
START_PROGRAM="/opt/oracle/scripts/start_nmgr.sh"
STOP_PROGRAM="/opt/oracle/scripts/stop_nmgr.sh"
STATUS_PROGRAM="/opt/oracle/scripts/status_nmgr.sh"
SERVICE_NAME=`/bin/basename $0`
LOCKFILE="/var/lock/subsys/$SERVICE_NAME"

RETVAL=0

start() {
        OLDPID=`/usr/bin/pgrep -f $PROCESS_STRING`
        if [ ! -z "$OLDPID" ]; then
            echo "$SERVICE_NAME is already running (pid $OLDPID) !"
            exit
        fi

        echo -n $"Starting $SERVICE_NAME: "
        /bin/su $DAEMON_USER -c $START_PROGRAM

        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $LOCKFILE
}

stop() {
        echo -n $"Stopping $SERVICE_NAME: "
        OLDPID=`/usr/bin/pgrep -f $PROCESS_STRING`
        if [ "$OLDPID" != "" ]; then
            # /bin/kill -TERM $OLDPID
            /bin/su $DAEMON_USER -c $STOP_PROGRAM
        else
            /bin/echo "$SERVICE_NAME is stopped"
        fi
        echo
        /bin/rm -f $NodeManagerLockFile
        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE

}

restart() {
        stop
        sleep 10
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|force-reload|reload)
        restart
        ;;
  condrestart|try-restart)
        [ -f $LOCKFILE ] && restart
        ;;
  status)
        /bin/su $DAEMON_USER -c $STATUS_PROGRAM
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
        exit 1
esac

exit $RETVAL

