#!/bin/bash
#
# profile for your weblogicuser -> customize to your environment
export TERM=xterm
export LC_ALL=en_US.utf8

export JAVA_HOME=/opt/java/jdk1.8_current                       # where your jdk is
export PATH=${JAVA_HOME}/bin:${PATH}

export MW_HOME=/opt/oracle/products/fmw                         # path to 'fmw' directory
export DOMAIN_HOME=/opt/oracle/Middleware/domains/esb_domain    # path to your weblogic domain